permalink: /:slug
theme: just-the-docs
plugins:
  - jemoji

sass:
  style: :compressed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - package-lock.json
  - commitlint.config.js

include:
  - _KIRI_
  - .*.svg.json
  - .options.json

just_the_docs:
  logo: "/assets/images/logo.png"
  search_enabled: true
  heading_anchors: true

project: 
  renders:
    - title: "Render Top Angled"
      image_suffix: "-3d_top_angled.png"
    - title: "Render Top"
      image_suffix: "-3d_top.png"
    - title: "Render Bottom"
      image_suffix: "-3d_bottom.png"

  schematic_variants:
    - name: "Dark"
      file_suffix: "-schematic-dark.pdf"
    - name: "Monochromatic"
      file_suffix: "-schematic-mono.pdf"
    - name: "Light"
      file_suffix: "-schematic-default.pdf"

  assembly_variants:
    - name: "Dark"
      file_suffix: "-pcb-dark.pdf"
    - name: "Light"
      file_suffix: "-pcb-light.pdf"
